version: '3.8'

services:
  bot:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    ports:
      - '3000:3000'
    depends_on:
      - redis
    volumes:
      - .:/app
    command: pnpm start

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'